spring:
  mail: 
    host: mail.grupocore.net
    username: tecnologia@quintoimpacto.net
    password: XXX
    port: 564    
  datasource: 
    url: jdbc:mysql://localhost:8889/depelos?useSSL=false&allowPublicKeyRetreival=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            
    hibernate:
        ddl-auto: update
        
            
  thymeleaf:
    cache: false 

